<?php

function icecapusa_user_login($account) {
  
  $current_path = \Drupal::service('path.current')->getPath();
  $result = \Drupal::service('path.alias_manager')->getAliasByPath($current_path);
  
  if ($result == "/buyer/login" || $result == "/buyer/register") {
  	$url = "/buyer/dashboard";
  	$response = new Symfony\Component\HttpFoundation\RedirectResponse($url);
  	$response->send();
  }

  if ($result == "/distributor/login" || $result == "/distributor/register") {
  	$url = "/distributor/dashboard";
  	$response = new Symfony\Component\HttpFoundation\RedirectResponse($url);
  	$response->send();
  }

  if ($result == "/administrator/dashboard") {
  	$url = "administrator/dashboard`";
  	$response = new Symfony\Component\HttpFoundation\RedirectResponse($url);
  	$response->send();
  }
}

function icecapusa_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  $current_path = \Drupal::service('path.current')->getPath();
  $result = \Drupal::service('path.alias_manager')->getAliasByPath($current_path);
  
  if ($result == "/buyer/login" || $result == "/buyer/register") {
    //print "<pre>";print_r($entity->roles);print "</pre>";exit;
    $entity->addRole('buyer');
  }

  if ($result == "/distribute/login" || $result == "/distribute/register") {
    $entity->addRole('distributor');
  }
}
